services:
  - type: web
    name: correio-elegante
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: BASE_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: correio-elegante-db
          property: connectionString
      - key: PYTHONIOENCODING
        value: utf-8
      - key: PYTHONUTF8
        value: "1"

databases:
  - name: correio-elegante-db
    databaseName: correio
    plan: free
